# version: '3.7'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    env_file:
      - .env

  backend:
    build: ./backend
    ports:
      - "3333:3333"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: cemdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
